# Generated by Django 6.0.6 on 2026-07-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Scheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FARMERS", "Agriculture / Farmers"),
                            ("EDUCATION", "Scholarships & Education"),
                            ("PENSIONS", "Social Security & Pensions"),
                            ("WOMEN", "Women Empowerment"),
                            ("HEALTH", "Healthcare & Subsidies"),
                            ("EMPLOYMENT", "Employment & Skill Development"),
                            ("OTHERS", "Others"),
                        ],
                        default="OTHERS",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "eligibility",
                    models.TextField(help_text="Eligibility criteria (who can apply)"),
                ),
                (
                    "required_documents",
                    models.TextField(help_text="List of documents required"),
                ),
                (
                    "apply_link",
                    models.URLField(
                        blank=True,
                        help_text="Link to external application portal",
                        null=True,
                    ),
                ),
                ("last_date", models.DateField(blank=True, null=True)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
    ]
