# Generated by Django 6.0.6 on 2026-07-04 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PRODUCE", "Fresh Vegetables & Crops"),
                            ("DAIRY", "Dairy & Poultry"),
                            ("HANDICRAFTS", "Handicrafts & Artworks"),
                            ("SERVICES", "Local Labor & Services (Tailoring, Repair)"),
                            ("OTHERS", "Others"),
                        ],
                        default="PRODUCE",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="Price in INR", max_digits=10
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(
                        help_text="Contact number for buyers", max_length=15
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
