# Generated by Django 6.0.6 on 2026-07-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VillageProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="e-Village Main", max_length=100)),
                ("district", models.CharField(default="Pune", max_length=100)),
                ("state", models.CharField(default="Maharashtra", max_length=100)),
                ("population", models.IntegerField(default=1500)),
                ("schools_count", models.IntegerField(default=2)),
                ("hospitals_count", models.IntegerField(default=1)),
                ("water_connections", models.IntegerField(default=350)),
                (
                    "panchayat_head",
                    models.CharField(default="Sarpanch Ramesh Patil", max_length=100),
                ),
                (
                    "about_text",
                    models.TextField(
                        default="Welcome to our digital village portal. We strive to empower our citizens through connectivity."
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        default="contact@evillage.gov.in", max_length=254
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(default="+91 9876543210", max_length=15),
                ),
            ],
        ),
    ]
