# Generated by Django 6.0.6 on 2026-07-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgricultureTip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CROP", "Crop Advisory"),
                            ("WEATHER", "Weather Alert"),
                            ("FERTILIZER", "Fertilizer & Soil Guidance"),
                            ("PEST", "Pest & Disease Control"),
                        ],
                        default="CROP",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "crop_name",
                    models.CharField(
                        blank=True,
                        help_text="e-Village specific crop (optional)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="agriculture/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MandiPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crop_name", models.CharField(max_length=100)),
                (
                    "price_per_quintal",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price in INR",
                        max_digits=10,
                        max_length=10,
                    ),
                ),
                (
                    "market_name",
                    models.CharField(default="Local Mandi", max_length=100),
                ),
                ("updated_at", models.DateField(auto_now=True)),
            ],
            options={
                "ordering": ["crop_name"],
            },
        ),
    ]
