# Generated by Django 5.2.7 on 2026-07-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agriculture", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agriculturetip",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="mandiprice",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
