# Generated by Django 5.2.7 on 2026-07-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agriculture", "0002_alter_agriculturetip_id_alter_mandiprice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agriculturetip",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="mandiprice",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
