# Generated by Django 6.0.6 on 2026-07-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EducationResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SCHOLARSHIP", "Scholarship Updates"),
                            ("STUDY_MATERIAL", "Digital Learning Resources"),
                            ("JOBS", "Local Jobs & Skill Training"),
                            ("EXAMS", "Competitive Exams Prep"),
                            ("SCHOOL_NOTICE", "School Notices & Events"),
                        ],
                        default="STUDY_MATERIAL",
                        max_length=25,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text="Direct link to resource or application portal",
                        null=True,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Upload notice PDF / resources",
                        null=True,
                        upload_to="education/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
