# Generated by Django 6.0.6 on 2026-07-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentGuide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "description",
                    models.TextField(
                        help_text="What this certificate/document is used for"
                    ),
                ),
                (
                    "required_documents",
                    models.TextField(
                        help_text="List of documents needed for application"
                    ),
                ),
                (
                    "processing_time",
                    models.CharField(default="15 Days", max_length=100),
                ),
                (
                    "official_link",
                    models.URLField(
                        blank=True,
                        help_text="Official application website link",
                        null=True,
                    ),
                ),
            ],
        ),
    ]
