# Generated by Django 6.0.6 on 2026-07-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HealthService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("DOCTOR", "Local Doctor / Clinic"),
                            ("AMBULANCE", "Ambulance Service"),
                            ("PHC", "Primary Health Centre (PHC)"),
                            ("VACCINE", "Vaccination Camp"),
                            ("EMERGENCY", "Emergency Helpline"),
                        ],
                        default="PHC",
                        max_length=20,
                    ),
                ),
                ("contact_number", models.CharField(max_length=20)),
                (
                    "timing",
                    models.CharField(
                        default="24/7",
                        help_text="e.g. 9:00 AM - 5:00 PM or 24/7",
                        max_length=100,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Services offered or medical specialization",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["service_type", "name"],
            },
        ),
    ]
